# Generated by Django 6.0.7 on 2026-07-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, default='')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('doctor_name', models.CharField(blank=True, default='', max_length=100)),
                ('frame_details', models.CharField(max_length=100)),
                ('lens_details', models.CharField(max_length=100)),
                ('frame_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lens_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('right_eye_sph', models.CharField(blank=True, default='', max_length=20)),
                ('right_eye_cyl', models.CharField(blank=True, default='', max_length=20)),
                ('right_eye_axis', models.CharField(blank=True, default='', max_length=20)),
                ('left_eye_sph', models.CharField(blank=True, default='', max_length=20)),
                ('left_eye_cyl', models.CharField(blank=True, default='', max_length=20)),
                ('left_eye_axis', models.CharField(blank=True, default='', max_length=20)),
                ('pd', models.CharField(blank=True, default='', max_length=20)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('AT_LAB', 'At Lab'), ('READY', 'Ready')], default='RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
